# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        exclude: "site/.*"
      - id: end-of-file-fixer
        exclude: "site/.*"
      - id: check-yaml
        exclude: "site/.*|helm/.*\.yaml$|apps/.*/helm/.*\.yaml$"
      - id: check-added-large-files

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: master
    hooks:
      - id: forbid-binary
        exclude: "site/.*"
      - id: require-ascii
        exclude: '\.(md|yml|yaml|sh|py)$|site/.*'
        
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        exclude: "site/.*|helm/.*\.yaml$|apps/.*/helm/.*\.yaml$"
