apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: netapp-mcp-server
  namespace: netapp-mcp
  labels:
    app: netapp-mcp-server
    version: v1.0.0
    component: mcp-server
  annotations:
    serving.knative.dev/creator: "netapp-integration"
    serving.knative.dev/lastModifier: "netapp-integration"
    description: "NetApp ActiveIQ Unified Manager MCP Server for AI assistants"
spec:
  template:
    metadata:
      labels:
        app: netapp-mcp-server
        version: v1.0.0
      annotations:
        # Autoscaling configuration
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/target: "100"
        autoscaling.knative.dev/targetUtilizationPercentage: "70"
        autoscaling.knative.dev/scaleDownDelay: "30s"
        autoscaling.knative.dev/scaleUpDelay: "0s"
        autoscaling.knative.dev/stableWindow: "60s"
        
        # Resource configuration
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: "gen2"
        
        # Networking
        run.googleapis.com/network-interfaces: '[{"network":"default","subnetwork":"default"}]'
        
        # Deployment metadata
        deployment.kubernetes.io/revision: "1"
    spec:
      # Container timeout (max time for handling a request)
      timeoutSeconds: 300
      
      # Response headers timeout
      responseStartTimeoutSeconds: 30
      
      # Idle timeout (scale to zero after this time)
      idleTimeoutSeconds: 600
      
      containers:
      - name: netapp-mcp-server
        image: netapp-mcp-server:latest
        imagePullPolicy: IfNotPresent
        
        # Port configuration
        ports:
        - name: http1
          containerPort: 8080
          protocol: TCP
        
        # Environment variables from secrets
        envFrom:
        - secretRef:
            name: netapp-activeiq-credentials
        
        # Additional environment variables
        env:
        - name: SERVICE_NAME
          value: "netapp-mcp-server"
        - name: SERVICE_VERSION
          value: "v1.0.0"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        
        # Resource limits and requests
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        
        # Health checks
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - "import asyncio; import sys; sys.exit(0)"
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        
        readinessProbe:
          exec:
            command:
            - python
            - -c
            - "import asyncio; import sys; sys.exit(0)"
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        
        # Security context
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          capabilities:
            drop:
            - ALL
        
        # Volume mounts for certificates (if needed)
        volumeMounts:
        - name: ca-certificates
          mountPath: /etc/ssl/certs/custom-ca.crt
          subPath: ca.crt
          readOnly: true
        
        # Startup probe for slow-starting containers
        startupProbe:
          exec:
            command:
            - python
            - -c
            - "import asyncio; import sys; sys.exit(0)"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
          successThreshold: 1
      
      # Volumes
      volumes:
      - name: ca-certificates
        secret:
          secretName: netapp-ca-cert
          optional: true
          defaultMode: 0644
      
      # Service account
      serviceAccountName: netapp-mcp-sa
      
      # Security context for the pod
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      
      # Node selection (optional)
      # nodeSelector:
      #   kubernetes.io/arch: amd64
      
      # Tolerations (optional)
      # tolerations:
      # - key: "example-key"
      #   operator: "Exists"
      #   effect: "NoSchedule"
      
      # Affinity rules (optional)
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: node-type
      #           operator: In
      #           values:
      #           - worker
