{{- if .Values.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "netapp-mcp-server.configMapName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "netapp-mcp-server.labels" . | nindent 4 }}
  annotations:
    {{- include "netapp-mcp-server.annotations" . | nindent 4 }}
data:
{{- with .Values.configMap.data }}
{{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
---
{{- if and .Values.secret.create (not .Values.netapp.existingSecret) }}
{{- include "netapp-mcp-server.validateNetApp" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netapp-mcp-server.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "netapp-mcp-server.labels" . | nindent 4 }}
    {{- with .Values.secret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: {{ .Values.secret.type }}
stringData:
  NETAPP_BASE_URL: {{ .Values.netapp.baseUrl | quote }}
  NETAPP_USERNAME: {{ .Values.netapp.username | quote }}
  NETAPP_PASSWORD: {{ .Values.netapp.password | quote }}
  NETAPP_VERIFY_SSL: {{ .Values.netapp.verifySSL | quote }}
  NETAPP_TIMEOUT: {{ .Values.netapp.timeout | quote }}
  LOG_LEVEL: {{ .Values.app.logLevel | quote }}
{{- end }}
