{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "netapp-mcp-server.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "netapp-mcp-server.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
---
{{- if and .Values.rbac.create .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "netapp-mcp-server.fullname" . }}-role
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "netapp-mcp-server.labels" . | nindent 4 }}
rules:
{{- with .Values.rbac.rules }}
{{- toYaml . | nindent 0 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "netapp-mcp-server.fullname" . }}-rolebinding
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "netapp-mcp-server.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "netapp-mcp-server.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: Role
  name: {{ include "netapp-mcp-server.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
